# Generated by Django 4.0.3 on 2022-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
