# Generated by Django 4.0.3 on 2022-04-01 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
